# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:40
from __future__ import unicode_literals

from django.db import migrations


def transaction_currency_signatures(apps, schema_editor):
    TransactionModel = apps.get_model('walletweb', 'Transaction')
    CurrencyModel = apps.get_model('walletweb', 'Currency')

    usd_currency = CurrencyModel()
    usd_currency.sign = '$'
    usd_currency.name = 'USD'
    usd_currency.rate = 1
    usd_currency.save()

    # set currency for transaction, and save to generate the sig
    for t in TransactionModel.objects.all():
        t.currency = usd_currency
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0007_auto_20161228_0855'),
    ]

    operations = [
        migrations.RunPython(transaction_currency_signatures)
    ]
