# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0011_auto_20161229_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagtransactions', to='walletweb.Tag'),
        ),
        migrations.AlterField(
            model_name='transactiontag',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactiontags', to='walletweb.Transaction'),
        ),
    ]
