# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 08:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0012_auto_20161229_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
