# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 07:09
from __future__ import unicode_literals

from django.db import migrations


def assigncurrencytotransactions(apps, schema_editor):
    TransactionModel = apps.get_model('walletweb', 'Transaction')

    nonecurrencytransactions = TransactionModel.objects.filter(currency__isnull=True)

    for trans in nonecurrencytransactions:
        trans_user = trans.account.user
        user_display_currency = trans_user.userprofile.display_currency

        trans.currency = user_display_currency
        trans.save()


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0014_userprofile'),
    ]

    operations = [
        migrations.RunPython(assigncurrencytotransactions)
    ]
