# Generated by Django 2.0.2 on 2018-04-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0021_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Is Processed'),
        ),
    ]
