# Generated by Django 2.0.3 on 2018-04-07 04:11

from django.db import migrations
from django.utils.text import slugify


def assignslugtotag(apps, schema_editor):
    Tag = apps.get_model('walletweb', 'tag')

    all_tags = Tag.objects.all()

    for tag in all_tags:
        tag.slug = slugify(tag.text)
        tag.save()


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0024_tag_slug'),
    ]

    operations = [
        migrations.RunPython(assignslugtotag)
    ]
