# Generated by Django 2.0.3 on 2018-04-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0025_auto_20180407_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='text',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
    ]
