# Generated by Django 2.0.3 on 2018-04-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0026_auto_20180407_0544'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'slug')},
        ),
    ]
