# Generated by Django 2.0.3 on 2018-04-07 06:21

from django.db import migrations
from django.utils.text import slugify

from moneytracker import settings


def makesureallusershaverighttags(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0027_auto_20180407_0545'),
    ]

    operations = [
        migrations.RunPython(makesureallusershaverighttags)
    ]
