# Generated by Django 2.0.3 on 2018-04-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0029_auto_20180407_0644'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='walletweb_account',
        ),
        migrations.AlterModelTable(
            name='currency',
            table='walletweb_currency',
        ),
        migrations.AlterModelTable(
            name='fileupload',
            table='walletweb_fileupload',
        ),
        migrations.AlterModelTable(
            name='recurringtransaction',
            table='walletweb_recurringtransaction',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='walletweb_tag',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='walletweb_transaction',
        ),
        migrations.AlterModelTable(
            name='transactiontag',
            table='walletweb_transactiontag',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='walletweb_userprofile',
        ),
        migrations.AlterModelTable(
            name='walletyuser',
            table='walletweb_walletyuser',
        ),
    ]
