# Generated by Django 2.0.3 on 2018-04-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0030_auto_20180408_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='walletweb.Account'),
        ),
    ]
