# Generated by Django 2.0.3 on 2018-04-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0031_auto_20180421_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walletweb.Account'),
        ),
    ]
