# Generated by Django 2.0.3 on 2018-04-21 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0032_auto_20180421_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
