# Generated by Django 2.0.3 on 2018-08-16 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0033_recurringtransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='walletweb.Account'),
        ),
    ]
