# Generated by Django 2.0.8 on 2018-09-09 10:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0034_fileupload_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Extra Information'),
        ),
    ]
