# Generated by Django 2.0.13 on 2020-03-13 12:06

from django.db import migrations, models


def rename_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')

    try:
        main_site = Site.objects.get(pk=1)
        main_site.domain = 'moneytracker.codedemigod.com'
        main_site.name = 'moneytracker'
        main_site.save()
    except models.ObjectDoesNotExist:
        print("Main site not found, continuing")


class Migration(migrations.Migration):

    dependencies = [
        ('walletweb', '0035_transaction_extra'),
    ]

    operations = [
        migrations.RunPython(rename_site)
    ]
